function k3 = calcScaleZ(W,wx1,wx2,wx3,wy1,wy2,wy3,wz1,wz2,wz3)
%CALCSCALEZ
%    K3 = CALCSCALEZ(W,WX1,WX2,WX3,WY1,WY2,WY3,WZ1,WZ2,WZ3)

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    03-Feb-2014 00:46:04

t2 = wx1.^2;
t3 = wy1.^2;
t4 = wx2.^2;
t5 = wy3.^2;
t6 = wx3.^2;
t7 = wy2.^2;
t8 = wz3.^2;
t9 = wz2.^2;
t10 = wz1.^2;
t11 = 1.0./W;
t12 = t3.*t4;
t13 = t2.*t5;
t14 = t6.*t7;
t23 = t2.*t7;
t24 = t3.*t6;
t25 = t4.*t5;
t15 = t12+t13+t14-t23-t24-t25;
t16 = 1.0./t15;
t17 = t2.*t5.*t9;
t18 = t3.*t4.*t8;
t19 = t6.*t7.*t10;
t26 = t2.*t7.*t8;
t27 = t4.*t5.*t10;
t28 = t3.*t6.*t9;
t20 = t16.*(t17+t18+t19-t26-t27-t28);
t21 = sqrt(t20);
t22 = t11.*t21;
k3 = t22;
