function k2 = calcScaleY(W,wx1,wx2,wx3,wy1,wy2,wy3,wz1,wz2,wz3)
%CALCSCALEY
%    K2 = CALCSCALEY(W,WX1,WX2,WX3,WY1,WY2,WY3,WZ1,WZ2,WZ3)

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    03-Feb-2014 00:46:02

t2 = wx1.^2;
t3 = wz1.^2;
t4 = wx2.^2;
t5 = wz3.^2;
t6 = wx3.^2;
t7 = wz2.^2;
t8 = wy3.^2;
t9 = wy1.^2;
t10 = wy2.^2;
t11 = 1.0./W;
t12 = t3.*t4;
t13 = t2.*t5;
t14 = t6.*t7;
t24 = t2.*t7;
t25 = t3.*t6;
t26 = t4.*t5;
t15 = t12+t13+t14-t24-t25-t26;
t16 = 1.0./t15;
t17 = t2.*t5.*t10;
t18 = t3.*t4.*t8;
t19 = t6.*t7.*t9;
t27 = t2.*t7.*t8;
t28 = t4.*t5.*t9;
t29 = t3.*t6.*t10;
t20 = t17+t18+t19-t27-t28-t29;
t21 = t16.*t20;
t22 = sqrt(t21);
t23 = t11.*t22;
k2 = t23;
